### ISSUE TITLE
The requested URL was not found on the server

### ISSUE THREAD

**Issue by minanagehsalalma** [bastien8060/MDPin#3] opened 2021-03-01 19:29 UTC
python on windows 10

![image](https://user-images.githubusercontent.com/20546638/109548214-08d91800-7ad5-11eb-85c5-a8918e86fd50.png)
![image](https://user-images.githubusercontent.com/20546638/109548230-0d9dcc00-7ad5-11eb-91a0-7f0d81335ac6.png)

**Comment by minanagehsalalma** [comment] 2021-03-01 19:58
also i tested it by manually opening the index file on UC browser and it's broken !

https://user-images.githubusercontent.com/20546638/109550755-5dca5d80-7ad8-11eb-900d-8d9e03277e68.mp4

**Comment by bastien8060** [comment] 2021-03-01 20:40
Which device do you use to test the webpage?
The link will only work to anything comnected to the same wifi. Otherwise you will need a VPS.

In doubt, if you have Google Chrome, try the webpage with a simulated smartphone with the same computer used to start the server (http://localhost:8075/web/index.html). [Here](https://www.browserstack.com/guide/view-mobile-version-of-website-on-chrome) is an example how to.

Check for errors that could help me using *inspect element*.

Which device do you use from the UC browser too? It seems your versions of UC browser is having issue with the JavaScript guestures. I could rework that.

Also, this project is only targeted at android smartphone but tablets will be supported too.

**Comment by bastien8060** [comment] 2021-03-01 20:50
Another question:
One device returned "Document not found" and another returned the page but animations didn't work?

Could you make sure the URL entered was the same in both browsers? Sorry it sounds really stupid from me to ask, but a small error even happens even to the best :)

Really try to give me as much information which might be relevent, like which device/browser/os/version are you using and this will be awesome.

**Comment by minanagehsalalma** [comment] 2021-03-01 20:51
>The link will only work to anything comnected to the same wifi

i am connected to the same network.

>Which device do you use from the UC browser too? It seems your versions of UC browser is having issue with the JavaScript guestures. I could rework that.
Also, this project is only targeted at android smartphone

i am using a Samsung note4

**Comment by bastien8060** [comment] 2021-03-01 20:51
If you can get me all that (or as much as you can) and I manage to reproduce the error, then I will fix the issue as fast as I can! Deal?

**Comment by minanagehsalalma** [comment] 2021-03-01 20:52
> Could you make sure the URL entered was the same in both browsers? Sorry it sounds really stupid from me to ask, but a small error even happens even to the best :)

they are the same 

and it's the latest version of UC browser.

**Comment by bastien8060** [comment] 2021-03-01 21:08
Perfect. Which devices do you use? Android smartphone? Did you try with Chrome on android? Did you try as well Chrome on pc with the smartphone simulator?

Thanks

Esit: sorry just saw you used a Note 4, my bad.

**Comment by bastien8060** [comment] 2021-03-01 21:08
I think i sense where the issue is leading.

**Comment by minanagehsalalma** [comment] 2021-03-01 21:13
> Did you try as well Chrome on pc with the smartphone simulator?

yeah same problem

**Comment by minanagehsalalma** [comment] 2021-03-01 21:13
> Did you try with Chrome on android?

not it didn't pop up as an option when trying to open the file.

**Comment by bastien8060** [comment] 2021-03-01 21:14
I would say there are few things to rule out:
- trying the adress with localhost instead of the ip like http://localhost:8075/web/index.html (only works with pc, with the device simulator)
- Screenshots of errors in developper tools (aka. Inspect element). You can google how to.
- trying chrome with device simulator on pc and chrome on your samsung note 4.
- also which device got the *Document not found* error?

Make sure you stay in portrait mode too, this would help it for sure.

**Comment by bastien8060** [comment] 2021-03-01 21:17
> > Did you try as well Chrome on pc with the smartphone simulator?
> 
> yeah same problem 

Is it having gestures issues or document not found?

**Comment by bastien8060** [comment] 2021-03-01 21:17
> > Did you try with Chrome on android?
> 
> not it didn't pop up as an option when trying to open the file.

Hows the result when you try?

**Comment by minanagehsalalma** [comment] 2021-03-01 21:26
> > > Did you try as well Chrome on pc with the smartphone simulator?
> > 
> > 
> > yeah same problem
> 
> Is it having gestures issues or document not found?

both if i don't open the file manually .

**Comment by minanagehsalalma** [comment] 2021-03-01 21:29
![image](https://user-images.githubusercontent.com/20546638/109561530-f5827880-7ae5-11eb-84a0-2452f8dbef55.png)

**Comment by bastien8060** [comment] 2021-03-01 21:33
So if you open the file manually (like file://Users/xyz/Desktop/MDPin/static/index.html) the page seems to load but however you get gestures issues.

If you try the url given by the script you get a Document not found error? 

Heres a few url I would try:
- http://locahost:8075/web/index.html (only on PC)
- http://192.168.1.5:8075/web/index.html (on smartphone and pc)
- http://127.0.0.1:8075/web/index.html (only on PC)

And tell me if any improvements.

**Edit**: *could you screenshot or copy paste the URL you are using? Are you starting the pwn.py script from the py directory?*

**Comment by bastien8060** [comment] 2021-03-01 21:41
I think i figured the issue! Either:
- It is an issue with relative path with windows
- Or it is an issue with the `plugin.py` script

Would you try at last navigating to the 'py' folder with cmd so that your cmd would look like `.../Downloads/compressed/MDPin-main/py>`

Then try from there launching pwn.py :)

I think it is the issue!

**Edit:** *To navigate to a folder with cmd, you can use:*
```cd [folder name]```
*like :*
```Users\test\Desktop\MDPin> cd py```

**Comment by bastien8060** [comment] 2021-03-01 21:42
> ![image](https://user-images.githubusercontent.com/20546638/109561530-f5827880-7ae5-11eb-84a0-2452f8dbef55.png)
> 

That would be because it cant find the backend, which has additional code. The server to the link given by the script handles it slightly differently.

**Comment by minanagehsalalma** [comment] 2021-03-01 21:45
> _Are you starting the pwn.py script from the py directory?_

yeah i figured it .. i was running it from the plugin.py file now it works 

but i don't get any requests from other devices in the same network nor the entered passwords.

while it works perfectly on the desktop with mobile emulator.

**Comment by bastien8060** [comment] 2021-03-01 21:48
Hmm did you correctly edit the config.json file in the static folder?

**Comment by bastien8060** [comment] 2021-03-01 21:49
I super glad it finally works now!

**Comment by bastien8060** [comment] 2021-03-01 21:49
Like said in the Readme, you should replace localhost with your ip in config.json in the static folder

**Comment by bastien8060** [comment] 2021-03-01 21:50
In your case it should be 192.168.1.5

**Comment by minanagehsalalma** [comment] 2021-03-01 21:52
> Like said in the Readme, you should replace localhost with your ip in config.json in the static folder

still the same problem

**Comment by bastien8060** [comment] 2021-03-01 21:52
In a future version, i will make it so the config.json is automatically generated!

Mind there are two config.json file. The one in question is in the static folder.

**Comment by bastien8060** [comment] 2021-03-01 21:54
Do you think you could get an error message like you did with chrome pc but for any device not working currently? Also how does your config.json look?

**Comment by minanagehsalalma** [comment] 2021-03-01 21:55
> Mind there are two config.json file. The one in question is in the static folder.

i know ... but the phone doesn't even send the password or left get requests as on desktop ... i monitored the traffic with http canary app.

just sends a get for the index page and nothing other than that.

**Comment by bastien8060** [comment] 2021-03-01 21:55
> > Like said in the Readme, you should replace localhost with your ip in config.json in the static folder
> 
> still the same problem

Even with 192.168.1.5? Maybe your ip changed. Check what the script suggests your IP is.

**Comment by minanagehsalalma** [comment] 2021-03-01 21:55
> Also how does your config.json look?

as it should

**Comment by bastien8060** [comment] 2021-03-01 21:56
> > Mind there are two config.json file. The one in question is in the static folder.
> 
> i know ... but the phone doesn't even send the password or left get requests as on desktop ... i monitored the traffic with http canary app.
> 
> just sends a get for the index page and nothing other than that.

When you changed the IP in the configs does the desktop version still work?

**Comment by minanagehsalalma** [comment] 2021-03-01 21:56
> Maybe your ip changed. Check what the script suggests your IP is.

no it didn't ... the page opens normally put nothing shows up on the cmd screen !

**Comment by bastien8060** [comment] 2021-03-01 21:58
Ohhh i think i figured this one too! I totally forgot because i turned off Cache. I think you should clear the cache now that you changed the config. I mean clear the cache on your smartphone in chrome settings.

**Comment by bastien8060** [comment] 2021-03-01 21:59
Another way to clear it is to try to reach the config.json from the url directly!

Edit: and refresh it multiple times! :)

**Comment by bastien8060** [comment] 2021-03-01 22:09
I added new ideas for improvements (#4) from our conversation by the way. Thank you very much for taking a bit of your time!

**Comment by minanagehsalalma** [comment] 2021-03-01 22:11
> Another way to clear it is to try to reach the config.json from the url directly!
> 
> Edit: and refresh it multiple times! :)

yeah thanks it worked ... but still kinda buggy in UC as it opens in landscape not portrait  ... so the reset of the screen is not showen.

**Comment by minanagehsalalma** [comment] 2021-03-01 22:12
> Thank you very much for taking a bit of your time!

U R welcome ... and thank you for the fun tool.

i will also come a bit later with some suggestion if you like to add ;)

**Comment by bastien8060** [comment] 2021-03-01 22:13
Okay i will add this to be fixed right away for  tomorrow morning first thing! (Its 11pm at my place)

**Comment by bastien8060** [comment] 2021-03-01 22:15
And thanks again! I will enlarge browser and test more on different browsers/OS. Ill add it right away in #4

**Comment by bastien8060** [comment] 2021-03-01 22:16
> > Thank you very much for taking a bit of your time!
> 
> U R welcome ... and thank you for the fun tool.
> 
> i will also come a bit later with some suggestion if you like to add ;)

That will be very appreciated! Thanks, and have a good one!

I'll close the issue for now, but feel free to open a discussion on the repo or talk on #4 for suggestions

**Comment by bastien8060** [comment] 2021-03-01 22:17
If any problem/s, feel free to reopen it or submit a new issue!

**Closed as completed** 2021-03-01 22:17 UTC
Labels: bug
